name: Check code format & lint

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm i
      - name: Check format
        run: npm run check-format
      - name: Linting
        run: npm run lint
